# Generated by Django 4.2.25 on 2025-10-16 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('seminario', 'Seminário'), ('palestra', 'Palestra'), ('minicurso', 'Minicurso'), ('semana', 'Semana Acadêmica')], max_length=50)),
                ('data_inicio', models.DateTimeField()),
                ('data_fim', models.DateTimeField()),
                ('horario', models.CharField(blank=True, max_length=100)),
                ('local', models.CharField(blank=True, max_length=200)),
                ('vagas', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
